ritterim/public-github-actions

- forks/persist-workspace/.github/workflows/test-with-name.yml
- forks/persist-workspace/.github/workflows/test.yml
- forks/persist-workspace/LICENSE
- forks/persist-workspace/README.md
- forks/persist-workspace/action.yml
As of Aug 2023, the LICENSE file is MIT, therefore our fork and modifications will also be MIT.
We'll be making some improvements / changes in the next PR to bring it in line with the variant that we've been using internally.
source: https://github.com/bissolli/gh-action-persist-workspace
> Fork of bissolli/gh-action-persist-workspace

- .github/workflows/calculate-version-with-npm-version-using-pr-labels.yml
A reusable GitHub Actions Workflow that looks at labels on the GitHub PR and figures out which 'npm version' command to use in order to bump the version.
> Create "Calculate NPM Version (PR Labels)" workflow

- forks/persist-workspace/LICENSE
- forks/persist-workspace/README.md
- forks/persist-workspace/action.yml
- Renamed 'artifactName' input to 'artifact_name'.
- The default action is 'persist'.
- Added 'retention_days' argument with a default of 3 days.
- Add 'artifact_name' output.  Also reworked the artifact name logic to include the GitHub run_id value.
- Route 'input.artifact_name' through an env variable. This helps protect against command-line injections in the 'run' statements later on.
- Exclude the '.git' folder.  There can be secrets written into the '.git/config' file.  By removing this folder, we eliminate a potential source of secrets leakage.
- Add GZIP compression.
> Refactor persist-workspace

- actions/npm-config-github-packages-repository/LICENSE
- actions/npm-config-github-packages-repository/action.yml
- actions/npm-config-myget-packages-repository/LICENSE
- actions/npm-config-myget-packages-repository/action.yml
- NPM scope names must be lower-case (a-z), numbers, periods, and hyphens.  The regex used to validate this is not super strict and limits the length to 60 chars.
ref: https://github.com/npm/validate-npm-package-name
- MyGet API keys are currently GUIDs.
- GitHub token regex is from a gist.
ref: https://gist.github.com/magnetikonline/073afe7909ffdd6f10ef06a00bc3bc88
> Add 'npm config' for MyGet / GitHub Pkgs actions

- .github/workflows/generate-github-token-from-github-app.yml
The previous version was missing the 'dist' folder.  See PR https://github.com/ritterim/public-github-actions/pull/12
> Upgrade to 96c9af28 of the github-app-token action

- .github/workflows/npm-packages-pr-build.yml
- .github/workflows/npm-packages-pr-create-tag.yml
These were tested out in a private repo to verify operation.
**npm-package-pr-build.yml:**
A read-only workflow that uses no GH secrets which will calculate the version based on PR labels, then execute the 'npm run build', 'npm run tests', 'npm pack' steps.
**npm-packages-pr-create-tag.yml:**
A workflow that runs 'npm version' and increments based on PR labels.  Then creates a release tag using a GH Token from a GH App with that version.
> Publish NPM Package PR build/tag reusable workflows

- .github/workflows/npm-packages-pr-create-tag.yml
This combines the work that this workflow did with the work done in pr-build so that we can fire this when a PR is closed instead of trying to trigger via 'on: workflow_run:'.
> Add build/test/pack steps to the create tag workflow

- actions/file-name-validator/LICENSE
- actions/file-name-validator/action.yml
- actions/npm-package-name-validator/LICENSE
- actions/npm-package-name-validator/action.yml
- actions/npm-package-scope-validator/LICENSE
- actions/npm-package-scope-validator/action.yml
- actions/path-name-validator/LICENSE
- actions/path-name-validator/action.yml
- actions/version-number-validator/LICENSE
- actions/version-number-validator/action.yml
These wrappers around the regex-validator action will make it so that we don't have to hardcode regex patterns in the individual workflows or other actions.
- file-name-validator: Allows 3-70 alphanumeric, dashes / periods / hyphens / plus-signs.
- path-name-validator: Allows 3-70 alphanumeric, dashes / periods / hyphens / plus-signs and slashes for the path separator.  Must end with a slash character.
- npm-package-name-validator: A strict package name validator for NPM packages.  Only allows 5-40 lower-case letters, numbers and hyphens.
- npm-package-scope-validator: A strict package scope validator for NPM packages. Only allows 5-25 lower-case letters, numbers and hyphens.
- version-number-validator: A regex pattern for matching SemVer style version numbers.  Has a switch to support a …
> Composite action wrappers for regex-validator

- actions/version-number-validator/action.yml
Composite actions do not support typing of the inputs and everything ends up as a string.  In order to allow version strings with a 'v' prefix, you must pass in the string value 'true' (lowercase).
Ref issue 2238 at https://github.com/actions/runner
> Fix the version-number-validator for 'v' prefixes

- actions/create-github-release/LICENSE
- actions/create-github-release/README.md
- actions/create-github-release/action.yml
A composite action which will create a GitHub Release using an existing tag in the GitHub repository.
> Publish 'create-github-release' composite action

- actions/attach-artifact-to-release/LICENSE
- actions/attach-artifact-to-release/README.md
- actions/attach-artifact-to-release/action.yml
Attach artifact from the workflow run to a GitHub Release.
> Publish 'attach-artifact-to-release' composite action

- .github/workflows/npm-create-github-release-with-artifact.yml
- ReusableWorkflows.md
Create a GitHub release using an existing tag, then attach a file from the runner artifact to the release. This only supports a single artifact file.
> Add npm-create-github-release-with-artifact.yml workflow

- .github/workflows/npm-packages-release-on-tag.yml
- .github/workflows/npm-publish-to-github-packages.yml
- .github/workflows/npm-publish-to-myget.yml
These were missing validation for the artifact_name and project_directory inputs.
> Add input validation to 'npm publish' workflows

- actions/npmjs-access-token-validator/LICENSE
- actions/npmjs-access-token-validator/action.yml
Meta-action which centralizes where we define the regex for an NPM token.
> Create npmjs-access-token-validator action

- .github/workflows/npm-publish-to-github-packages.yml
- .github/workflows/npm-publish-to-myget.yml
- BREAKING_CHANGES.md
The NPM publish workflows no longer take in `project_directory` as an input.
AFAIK, the 'npm publish' command does not look at the package.json file in the current directory. But instead looks at the contents of the tar/gzip (tgz) file.
> [BREAKING] Remove project_directory publish workflow

- .github/workflows/calculate-version-with-npm-version-using-pr-labels.yml
- .github/workflows/extract-version-from-npm-package-json.yml
- .github/workflows/generate-github-token-from-github-app.yml
- .github/workflows/npm-build.yml
- .github/workflows/npm-create-github-release-with-artifact.yml
- .github/workflows/npm-create-version-tag.yml
- .github/workflows/npm-pack.yml
- .github/workflows/npm-packages-pr-build.yml
- .github/workflows/npm-packages-pr-create-tag.yml
- .github/workflows/npm-packages-release-on-tag.yml
- .github/workflows/npm-test.yml
- actions/attach-artifact-to-release/README.md
- actions/attach-artifact-to-release/action.yml
- actions/create-github-release/README.md
- actions/create-github-release/action.yml
- actions/file-name-validator/action.yml
- actions/github-token-validator/action.yml
- actions/npm-config-github-packages-repository/README.md
- actions/npm-config-github-packages-repository/action.yml
- actions/npm-config-myget-packages-repository/README.md
- actions/npm-config-myget-packages-repository/action.yml
- actions/npm-config-npmjs-org-registry/action.yml
- actions/npm-package-name-validator/action.yml
- actions/npm-package-scope-validator/action.yml
- actions/npmjs-access-token-validator/action.yml
- actions/path-name-validator/action.yml
- actions/version-number-validator/action.yml
Have all of the actions/workflows start referencing the v1.3.0 release which is being tested this week.
> Bump versions to prepare for upcoming v1.3.0 release

- .github/workflows/npm-packages-release-on-tag.yml
In v1.3, there is a new input (artifact_file_path) to these workflows.  This way there is no guessing or assumptions about what the filename actually is.
> Add missing 'artifact_file_path' input to workflow

- .github/workflows/npm-packages-release-on-tag.yml
- .github/workflows/npm-publish-to-myget.yml
If the caller is not specifying that they want to publish to MyGet then they don't need to specify the API key. We do checks inside the called actions/workflows to prevent an empty key from being accepted.
> Tweak myget_api_key description, make optional

- actions/attach-artifact-to-release/action.yml
- actions/create-github-release/action.yml
Private repositories can't be called from public repos (or actions running in public repos).
> Switch to use the public github-token-validator

- README.md
- actions/attach-artifact-to-release/action.yml
- actions/create-github-release/action.yml
- actions/github-org-repository-validator/LICENSE
- actions/github-org-repository-validator/action.yml
Validate that the value looks like a GitHub repository in the format of "{org}/{name}".  It only allows
alphanumeric names plus hyphens.
> Add github-org-repository-validator action

- actions/file-path-name-validator/LICENSE
- actions/file-path-name-validator/action.yml
For situations where the file path and file name are part of the same string value.
> Add file-path-name-validator action

- actions/file-path-name-validator/action.yml
The file_path_name input was not being passed to the regex validator.
> Fix bug in file-path-name-validator

- actions/regex-validator/tests/validate-input.test.ts
- actions/regex-validator/tsconfig.json
Switch from node:test to jest/globals.  Add some tests around the version string regex which shows how to setup a set of test cases.
```
PASS  tests/validate-input.test.ts
Validate Input Required False
✓ returns valid if required is false (1 ms)
✓ returns false result if input is empty string (1 ms)
✓ returns false result if input is empty string
✓ returns invalid if require and input are empty
Validate Input Required True
✓ matched returns true result
✓ matched returns true result with case insensitive (1 ms)
✓ returns result string
Error Message
✓ displays error
ValidateInput: Version RegEx
✓ Case: '0.0.1-alpha3' returns true (1 ms)
✓ Case: '0.900.85948-alpha3.2+abcdef' returns true
✓ Case: '1.2.0' returns true
✓ Case: '1.A.0' returns false (1 ms)
Test Suites: 1 passed, 1 total
Tests: …
```
> regex-validator: Import from '@jest/globals', add version regex tests

- actions/regex-validator/tests/validate-input.test.ts
Without this, the backslashes get interpreted by TS/JS prior to being fed into the RegEx validator.
Also, change the RegEx to something that is obviously broken.
> regex-validator (tests) Use String.raw when there are backslashes

- .github/workflows/calculate-version-with-npm-version-using-pr-labels.yml
- .github/workflows/npm-build-test.yml
- .github/workflows/npm-build.yml
- .github/workflows/npm-pack.yml
- .github/workflows/npm-test.yml
- .github/workflows/verify-tag-is-on-allowed-branch.yml
In situations where the job specifies a default working-directory for a run statement, where that directory only exists after checkout; we need to reorder the steps.
The alternative choice would be to specify a "./" working-directory for the steps that don't have to be run from a subdirectory.  This is good for those debug statements examining the github.ref value prior to doing the checkout.
> fix: job steps which need to run in sub-directory

- .github/workflows/npm-build-test.yml
For situations where someone needs to pass the npm_scope input down into the GH Packages config step.
Note that in most cases, users from other organizations will want to create a copy of workflows like this to be customized for their needs.
> Add ability to pass npm_scope down to GH config

- README.md
- actions/calculate-version-from-txt-using-github-run-id/LICENSE
- actions/calculate-version-from-txt-using-github-run-id/README.md
- actions/calculate-version-from-txt-using-github-run-id/action.yml
Calculates the version using a `version.txt` file and GitHub "`github.run_id`" value. This will increment the patch value roughly every 15 minutes.
> Add calculate-version-from-txt-using-github-run-id action

- README.md
Or at least, our current plan for how version tags and releases happen.
> Describe the release process

- .github/workflows/dotnet-test.yml
Because this is a temporary database, not exposed to the world, and thrown away right after the workflow finishes -- we can just make up a password from the run values.
> [BREAKING] Remove MSSQL password from dotnet-test.yml

- .github/workflows/verify-tag-is-on-allowed-branch.yml
In the verify-tag-is-on-allowed-branch.yml file, we only allowed branch names of length 3-50 instead of 2-50.
> [bug] Allow for shorter branch names in "verify tag"

- .github/workflows/verify-tag-is-on-allowed-branch.yml
Found another spot where we only looked at length 3-50 for branch names, which precluded branches like "v5".
> [bug] Update TAGGEDBRANCHES search to allow 2-50 len

- actions/regex-validator/src/validate.ts
- actions/regex-validator/tests/validate-input.test.ts
Before we were only returning an error message if the `re.test` broke. This adds logic based on the results of the `re.test` method. If the input doesn't match the regex expression passed in then it will return `false` with the generic error message.
> Regex | Returns Results of Test Method 

- forks/persist-workspace/action.yml
There are times when we need to juggle two or more persisted workspaces, such as in a repository with multiple build jobs.  This adds randomized suffix (of about 96 bits) to the artifact name.
> Add a random suffix for persisted workspace name

- .github/workflows/dotnet-publish.yml
When building Azure Functions, the DLLs get put down in a 'bin/' folder instead of at the root of the app.
We'll also add the recursive option to the 'ls -l app/' step.
> Remove the DLL check for 'dotnet publish'

- .github/workflows/dotnet-build.yml
- .github/workflows/dotnet-npm-build.yml
- .github/workflows/dotnet-npm-test.yml
- .github/workflows/dotnet-pack.yml
- .github/workflows/dotnet-publish.yml
- .github/workflows/dotnet-test.yml
In situations where we have multiple C# solutions, the NuGet cache key should also be different by path.
Instead of looking at all csproj files in the repository, we only want to look at csproj files at or below the non-root project directory.
> The NuGet cache key should respect the project dir

- forks/persist-workspace/action.yml
Building upon the previous idea of adding a random string to the artifact name; this will allow the caller to specify that suffix portion of the name if they want something more meaningful.
Allows for 2-40 alphanumeric characters.  If not provided, it falls back to the ~96 bit random string.
> Add artifact_name_suffix to persist-workspace

- .github/workflows/dotnet-build.yml
- .github/workflows/dotnet-npm-build.yml
- .github/workflows/npm-build-test-public.yml
- .github/workflows/npm-build-test.yml
- .github/workflows/npm-build.yml
- forks/persist-workspace/action.yml
Allow the caller, for reusable workflows which can persist the workspace, to specify the suffix for
the artifact.  Otherwise it will default to a random alphanumeric suffix to ensure uniqueness.
> Add persisted_workspace_artifact_suffix input

- forks/persist-workspace/action.yml
When the inputs.artifact_name_suffix value is not provided, the code did not correctly fall back to the randomized suffix.
https://stackoverflow.com/a/2013589
> Fix bug in persist-workspace around custom suffixes

- .github/workflows/dotnet-packages-pr-build.yml
- .github/workflows/dotnet-private-packages-release-build.yml
These are used for our repos that produce only NuGet packages (no website artifacts).
- Includes JFrog XRay audit/scan jobs.
- Pushes to GitHub Packages.
- Does *not* yet push to JFrog Artifactory.
In most cases, you would heavily customize these for your usage and not consume it directly.
> Add our dotnet package build workflows

- actions/jfrog-artifactory-repository-name-validator/LICENSE
- actions/jfrog-artifactory-repository-name-validator/action.yml
A validator for JFrog Artifactory repository names which only allows alphanumeric (mixed case) and hyphens.
https://jfrog.com/whitepaper/best-practices-structuring-naming-artifactory-repositories/
> Add jfrog-artifactory-repository-name-validator

- .github/workflows/jfrog-xray-audit.yml
- The "jfrog_api_url" input has changed names to "jfrog_api_base_url".
- Adds the required "jfrog_xray_watch_list" input.
- Changes to a text file for the report result instead of JSON.
> [BREAKING] Updated JFrog XRay Audit workflow

- .github/workflows/dotnet-push-github.yml
Doing the wildcard resulted in *.snupkg files erroring out because 'dotnet nuget push' is already going to send them along with the '.nupkg' file.
> Only push "*.nupkg" with dotnet nuget push

- .github/workflows/jfrog-xray-audit.yml
This way we can capture the .txt output file into an artifact attached to the build.  Or push the text output into a PR, or whatever else we decide to do.
> Add 'continue-on-error: true' to 'jf audit' step

- .github/workflows/jfrog-xray-audit.yml
The jfrog-xray-audit.yml reusable workflow has no need for the 'id-token: write' or 'packages: read' permissions. If we're using JFrog, then we'll be pulling everything out of Artifactory instead of GitHub Packages.
> Remove excess GH token permissions from 'jf audit'

- .github/workflows/dotnet-test-jfrog.yml
Using JFrog Artifactory as the sole package provider for NuGet files makes things different enough from the base 'dotnet-test.yml' file to be worth a separate workflow.
> Create dotnet-test-jfrog.yml reusable workflow

- .github/workflows/dotnet-pack.yml
We should be able to get away with not needing to access any NuGet package feeds (such as GH Pkgs) when doing the 'dotnet pack' step.
> Remove 'packages: read' perm from dotnet-pack.yml

- .github/workflows/dotnet-packages-pr-build.yml
- .github/workflows/dotnet-private-packages-release-build.yml
Switch to using 'dotnet-build-jfrog.yml' and the 'dotnet-test-jfrog.yml' variants for build/test. This requires additional inputs to these two workflows to handle passing the JFrog user name.
It also switches the build/test steps to only pull packages via the JFrog Artifactory virtual repo so that everything flows through JFrog security.
> Switch NuGet package workflows to use JF builds [BREAKING]

- .github/workflows/dotnet-build-jfrog.yml
When testing this out locally, sometimes we need the fuller URL and sometimes we don't.
> Drop the 'v3/' and 'index.json' from the JFrog URL

- .github/workflows/dotnet-build-jfrog.yml
Reverts ritterim/public-github-actions#116
This definitely made things worse.
> Revert "Drop the 'v3/' and 'index.json' from the JFrog URL"

- .github/workflows/dotnet-build-jfrog.yml
- .github/workflows/dotnet-test-jfrog.yml
- Use a bit of magic to remove any pre-defined NuGet source
- Have a separate 'dotnet restore' step
- Set verbosity for 'dotnet restore' to 'normal'
> Rework how we pull from JFrog virtual repos

- .github/workflows/dotnet-build-jfrog.yml
- .github/workflows/dotnet-test-jfrog.yml
This reverts commit b2104f22948a284c2d747f94b05d49ea8d59469c.
We found a setting in the JFrog Artifactory remote repo advanced settings named "Synchronize properties".
If this setting is not turned on, Artifactory will only fetch metadata from the upstream feed and will *not* fetch the package binary artifact associated with the metadata.
> Revert "Temporary fix for JFrog Artifactory proxy issues"

- actions/regex-validator/package-lock.json
- actions/regex-validator/package.json
Security update - moves Vite to version `4.5.2`. @tgharold do we need to update the `package.json` in `/forks/github-app-token` as well?
> Vite Update 4.5.2

- .github/workflows/dotnet-npm-astro-build-test-publish.yml
A combined .NET / NPM / Astro build process that produces an artifact for deployment.  It's useful in situations where you are using Astro and the build directory is very large and/or you don't want to persist between steps.
The downside, of course, is that there's more to dig through in the log if this combination job fails.
> Add dotnet-npm-astro-build-test-publish.yml

- .github/workflows/dotnet-build-jfrog.yml
- .github/workflows/dotnet-pack-jfrog.yml
- Move to using OIDC integration with JFrog (BREAKING)
- Stop using JFrog API key authentication (BREAKING)
- Generate JFrog build-info during the steps
- Use the composite/aggregate approach for build-info
> BREAKING: New versions of JFrog .NET build/pack steps

- .github/workflows/dotnet-test-jfrog.yml
- BREAKING: Move to using OIDC integration with JFrog
- BREAKING: Stop using JFrog API key authentication
- Generate JFrog build-info during the steps
- Use the composite/aggregate approach for build-info
> New versions of JFrog .NET test step (BREAKING)

- .github/workflows/jfrog-xray-audit.yml
- BREAKING: Move to using OIDC integration with JFrog
- BREAKING: Stop using JFrog API key authentication
> BREAKING: Switch JFrog audit to OIDC integration

- .github/workflows/dotnet-packages-pr-build-jfrog.yml
- .github/workflows/dotnet-private-packages-release-build-jfrog.yml
Also fix where we were pointing to for the JFrog audit job workflow.
> Update meta JFrog builds to use v1.14.0-rc4

- .github/workflows/dotnet-pack-jfrog.yml
Putting "continue-on-error: true" on the step that uploads ".nupkg" files to JFrog Artifactory should not have been added.
If we fail to upload any packages to Artifactory, the job should fail.
> The JFrog "upload *.nupkg" step should fail if fail

- .github/workflows/dotnet-publish.yml
Adds a new required input to specify the publish working directory instead of defaulting to the project_directory.
This reflects changes that we had to do in the JFrog-specific publish workflow in order to support JFrog build-info JSON.
Since we need that change there, making it here keeps the two versions of the publish workflow more compatible with each other.
> Improved dotnet-publish.yml (BREAKING)

- .github/workflows/dotnet-build-jfrog.yml
- .github/workflows/dotnet-publish-jfrog.yml
- .github/workflows/dotnet-test-jfrog.yml
Refactor how the build names get passed around between build/test/pack/publish steps.
Add the dotnet-publish-jfrog.yml script.
Publish JFrog build info in situations where we weren't before.
> Update JFrog .NET build scripts

- .github/workflows/calculate-version-from-txt-using-github-run-id.yml
- .github/workflows/calculate-version-with-npm-version-using-pr-labels.yml
- .github/workflows/dotnet-build-jfrog.yml
- .github/workflows/dotnet-build.yml
- .github/workflows/dotnet-frogbot-private-repo-scan.yml
- .github/workflows/dotnet-npm-astro-build-test-publish.yml
- .github/workflows/dotnet-npm-build.yml
- .github/workflows/dotnet-pack-jfrog.yml
- .github/workflows/dotnet-publish-jfrog.yml
- .github/workflows/dotnet-publish.yml
- .github/workflows/dotnet-push-jfrog-artifactory.yml
- .github/workflows/dotnet-test-jfrog.yml
- .github/workflows/extract-version-from-npm-package-json.yml
- .github/workflows/jfrog-publish-aggregate-build-info.yml
- .github/workflows/npm-build-test-public.yml
- .github/workflows/npm-build-test-publish.yml
- .github/workflows/npm-build-test.yml
- .github/workflows/npm-build.yml
- .github/workflows/npm-create-version-tag.yml
- .github/workflows/verify-tag-is-on-allowed-branch.yml
- actions/calculate-version-from-txt-using-github-run-id/README.md
- forks/persist-workspace/.github/workflows/test-with-name.yml
- forks/persist-workspace/.github/workflows/test.yml
- forks/persist-workspace/README.md
The older v3 uses Node v16 which is deprecated
and causes warnings on the GitHub Actions
run.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Upgrade to actions/checkout@v4

- forks/persist-workspace/action.yml
This is a bug fix for 1.15.1 -- as persist-workspace 1.15.1 didn't upgrade both the upload and download actions to the same major version.
> Upgrade persist-workspace to download-artifact@v4 (bug fix)

- .github/workflows/dotnet-build-jfrog.yml
- .github/workflows/dotnet-build.yml
- .github/workflows/dotnet-frogbot-private-repo-scan.yml
- .github/workflows/dotnet-npm-astro-build-test-publish.yml
- .github/workflows/dotnet-npm-build.yml
- .github/workflows/dotnet-npm-test.yml
- .github/workflows/dotnet-pack-jfrog.yml
- .github/workflows/dotnet-pack.yml
- .github/workflows/dotnet-publish-jfrog.yml
- .github/workflows/dotnet-publish.yml
- .github/workflows/dotnet-test-jfrog.yml
- .github/workflows/dotnet-test.yml
- .github/workflows/jfrog-publish-aggregate-build-info.yml
- .github/workflows/jfrog-xray-audit.yml
v3 used Node16, v4 uses Node20
Nothing of note in the v4 release
https://github.com/actions/cache/releases/tag/v4.0.0
> Upgrade to actions/cache@v4 (Node v20)

- .github/workflows/dotnet-build-jfrog.yml
- .github/workflows/dotnet-build.yml
- .github/workflows/dotnet-frogbot-private-repo-scan.yml
- .github/workflows/dotnet-npm-astro-build-test-publish.yml
- .github/workflows/dotnet-npm-build.yml
- .github/workflows/dotnet-npm-test.yml
- .github/workflows/dotnet-pack-jfrog.yml
- .github/workflows/dotnet-pack.yml
- .github/workflows/dotnet-publish-jfrog.yml
- .github/workflows/dotnet-publish.yml
- .github/workflows/dotnet-test-jfrog.yml
- .github/workflows/dotnet-test.yml
- .github/workflows/jfrog-publish-aggregate-build-info.yml
v3 used Node16, v4 uses Node20
Nothing notable on the releases page for v4
https://github.com/actions/setup-dotnet/releases/tag/v4.0.0
> Upgrade to actions/setup-dotnet@v4

- .github/workflows/__pr-build-actions-regex-validator.yml
This will help reduce the Node16 deprecation warnings.
> Upgrade the build for the regex-validator to v1.15.5

- .github/workflows/extract-version-from-npm-package-json.yml
Bring this workflow in line with the outputs from the other calculate version workflows.
> Add build date/timestamp outputs to extract NPM version workflow

- .github/workflows/calculate-version-with-npm-version-using-pr-labels.yml
When running on a PR build (not yet merged), the hash from PULL_REQUEST_HEAD_SHA does not yet exist in
a way that is visible to "git show".
So it's better to use "HEAD" as the ref here.
fix for #178
> Use HEAD for the NPM git commit date/time calcs

- .github/workflows/calculate-version-from-txt-using-github-run-id.yml
Output the git commit date/timestamp in the workflow. Prepare to use v1.16.5 of the underlying action.
> Update the calculate version.txt workflow with git

- .github/workflows/deploy-zip-to-azure-webapps-with-swap.yml
This version of the deploy step is designed for Linux Web App instances in Azure which do not support the "auto-swap when healthy" for the staging slot.
Deploy your artifact to the 'staging' slot as normal, then use this action to wait for it to go health before swapping the artifact into the 'production' slot.
> Add deploy-zip-to-azure-webapps-with-swap.yml

- .github/workflows/deploy-zip-to-azure-webapps-with-verify.yml
Add steps to the "with swap" workflow to call the new actions/health-and-version-check GitHub action to validate that the specified version string appears at the version URI. If we don't see the version string, we should reboot once and check again for another 300 seconds.
There is also a "with-verify" workflow added which can be used for situations where we deploy to a specific slot and won't be doing a "swap when ready" to the production slot.
Both of these are very useful on Linux Azure Web Apps where the Linux Web App sometimes goes into a zombie-like mode and doesn't restart automatically when a new zip artifact is deployed.
> Add actions/health-and-version-check@v1.17.0 steps

- .github/workflows/deploy-zip-to-iis7.yml
- Requires an IIS Deploy zip file
- Need a parameter XML file for the target site/app
- Uses basic (username+password) authentication
- MSDeploy must be installed and in the PATH
> Publish IIS deploy zip via IIS management port

- .github/workflows/jfrog-publish-aggregate-build-info.yml
Without this, the 'actions/setup-dotnet@v4' step might pull in a version you don't want.
> Add missing dotnet_version input on JFrog build-info

- .github/workflows/jfrog-publish-aggregate-build-info.yml
If we're using JFrog Artifactory, we no longer need to auth to GitHub Packages.  Nor should we be reading from GitHub Packages for the NuGet feed.
> Breaking: Remove GH Package in JFrog build-info

- .github/workflows/calculate-version-from-txt-using-github-run-id.yml
- .github/workflows/deploy-zip-to-azure-webapps.yml
- .github/workflows/dotnet-npm-build.yml
- .github/workflows/dotnet-publish.yml
- .github/workflows/dotnet-test.yml
The older non-JFrog workflows still used the v3
version of upload-artifact and download-artifact
due to intermediate workflows referencing older
versions of other workflows.
Update everything to point at the floating v1.17 tag.
> Update older .NET/NPM reusable workflows

- .github/workflows/npm-build.yml
Builds in Rimbot are failing because it's trying to use the deprecated version of "actions/download-artifact 3" - this updates npm-build to match our other builds process in using V4
> NPM Build Version Update

- .github/workflows/dotnet-build-jfrog.yml
Include an optional input for `github_job_runner_spec` to allow .NET 3.1 builds to run on a pinned build runner.
> Add github_job_runner_spec input on JFrog dotnet build

- .github/workflows/dotnet-pack-jfrog.yml
- .github/workflows/dotnet-publish-jfrog.yml
Include an optional input for `github_job_runner_spec` to allow .NET 3.1 pack and publish workflows to run on a pinned build runner.
Follow-up to adding this same input parameter to the build workflow: https://github.com/ritterim/public-github-actions/pull/225
> Add github_job_runner_spec input on JFrog dotnet pack and publish

- .github/workflows/dotnet-build-jfrog.yml
- .github/workflows/dotnet-build.yml
- .github/workflows/dotnet-npm-build-jfrog.yml
- .github/workflows/dotnet-npm-test-jfrog.yml
- .github/workflows/dotnet-npm-test.yml
- .github/workflows/dotnet-pack-jfrog.yml
- .github/workflows/dotnet-publish-jfrog.yml
- .github/workflows/dotnet-push-jfrog-artifactory.yml
- .github/workflows/dotnet-test-jfrog.yml
- .github/workflows/generate-github-token-from-github-app.yml
- .github/workflows/jfrog-publish-aggregate-build-info.yml
- .github/workflows/npm-build-jfrog.yml
- .github/workflows/npm-build-test-public.yml
- .github/workflows/npm-build-test.yml
- .github/workflows/npm-pack-jfrog.yml
- .github/workflows/npm-pack.yml
- .github/workflows/npm-test-jfrog.yml
- .github/workflows/npm-test.yml
Use the floating tag for all instances of forks/persist-workspace.
The last change to this action was April 2024 (v1.15.4) when it was upgraded to use the v4 upload/download actions.  Therefore moving from v1.16.0 to v1.17 should have no impact.
Moving to the floating v1.17 tag will make it easier to pickup any bug fixes / vulnerability fixes down the road.
> Upgrade 'forks/persist-workspace' action to v1.17

- actions/attach-artifact-to-release/README.md
- actions/calculate-version-from-txt-using-github-run-id/README.md
- actions/create-github-release/README.md
- actions/npm-config-github-packages-repository/README.md
- actions/npm-config-myget-packages-repository/README.md
- actions/npm-config-npmjs-org-registry/README.md
- forks/github-app-token/README.md
Our current recommendation is that we reference the floating 'v1.17' tag in our downstream actions so that we immediately pickup on any bug fixes in a newer patch release on the 'v1.17' line.
> Update READMEs to show use of floating 'v1.17' tag

- actions/terraform-apply-plan-file/action.yml
This input is only used in some of our Terraform plan/apply cycles where we deploy Azure Web Apps.  RIMbot is our internal GitHub issue/PR tool that we use for deployments, restarts, swaps, etc.
In order for it to work, we have to keep a list of the web apps that RIMbot is supposed to know about and we refresh that using our Terraform plans and a Powershell script.
> Make rimbot_registry_access_key optional, add notes
