.github/workflows/npm-build.yml
.github/workflows/npm-pack.yml
.github/workflows/npm-test.yml

Our standard npm build / test / pack reusable workflows.

Publish npm build/test/pack reusable workflows

---

forks/github-app-token/LICENSE
forks/github-app-token/README.md
forks/github-app-token/action.yml
forks/github-app-token/package-lock.json
forks/github-app-token/package.json
forks/github-app-token/src/fetch-installation-token.ts
forks/github-app-token/src/index.ts
forks/github-app-token/src/vite-env.d.ts
forks/github-app-token/tsconfig.json
forks/github-app-token/vite.config.ts

Change fetchInstallationToken() to return more of the result of the createInstallationAccessToken() call.  This makes it easier to figure out what is going on with the call and whether we are getting back the permissions that we requested.
cc: @eridolfi12 and @andrewrady

Refactor github-app-token to provide more info

---

.github/workflows/calculate-version-with-npm-version-using-pr-labels.yml
.github/workflows/extract-version-from-npm-package-json.yml
.github/workflows/generate-github-token-from-github-app.yml
.github/workflows/npm-build.yml
.github/workflows/npm-create-version-tag.yml
.github/workflows/npm-pack.yml
.github/workflows/npm-packages-pr-build.yml
.github/workflows/npm-packages-pr-create-tag.yml
.github/workflows/npm-packages-release-on-tag.yml
.github/workflows/npm-publish-to-github-packages.yml
.github/workflows/npm-publish-to-myget.yml
.github/workflows/npm-test.yml
BREAKING_CHANGES.md
README.md
ReusableWorkflows.md

Create documentation for the workflows and actions within the repository.

Add documentation for just about everything

---

.github/workflows/calculate-version-with-npm-version-using-pr-labels.yml
.github/workflows/extract-version-from-npm-package-json.yml
.github/workflows/npm-build.yml
.github/workflows/npm-create-version-tag.yml
.github/workflows/npm-pack.yml
.github/workflows/npm-packages-pr-build.yml
.github/workflows/npm-packages-pr-create-tag.yml
.github/workflows/npm-packages-release-on-tag.yml
BREAKING_CHANGES.md

Change 'package_filename' and 'package_lock_filename' to be 'package_json_filename' for clarity.
(This will go out in the upcoming v1.2.0 release.)

[BREAKING] Change to package_filename input name

---

actions/github-token-validator/LICENSE
actions/github-token-validator/action.yml

Create the meta-validator for GitHub tokens to centralize the regex location.

Create github-token-validator action

---

README.md
actions/npm-config-npmjs-org-registry/LICENSE
actions/npm-config-npmjs-org-registry/README.md
actions/npm-config-npmjs-org-registry/action.yml

This should be what is needed to configure 'npm' for the push into the public NPM registry.

Create npm-config-npmjs-org-registry action

---

README.md

Some of the newer actions were missing links.

Add link to releases page, add other actions

---

.github/workflows/npm-publish-to-npmjs-org.yml

The testing in the previous PR looks like everything works.

Remove "--dry-run" from 'npm publish' to npmjs.org

---

actions/attach-artifact-to-release/action.yml
actions/create-github-release/action.yml

Changed part of the URL in the prior PR, but forgot to change the rest of the URL.

Actually point at the public actions repo

---

.github/workflows/npm-pr-build-test.yml

A simple reusable workflow that runs 'npm run build' and 'npm run test' against the given project directory.

Add npm-pr-build-test.yml

---

.github/workflows/__pr-build-actions-regex-validator.yml

We want this to run whenever files are changed under actions/regex-validator.

Setup tests for actions/regex-validator

---

.github/workflows/calculate-version-from-txt-using-github-run-id.yml
ReusableWorkflows.md

Add the reusable workflow for version.txt + run_id

---

.github/workflows/npm-packages-release-on-tag.yml

[BREAKING] Stop pull/push from MyGet NPM registry

---

README.md
actions/version-number-major-minor-validator/LICENSE
actions/version-number-major-minor-validator/action.yml

Validate that the version string looks like a "major.minor" version number with only two numeric segments.

Add version-number-major-minor-validator

---

actions/guid-validator/LICENSE
actions/guid-validator/action.yml
actions/regex-validator/tests/validate-input.test.ts

Handles standard GUIDs, without the curly braces.

Add a GUID validator

---

.github/workflows/dotnet-packages-pr-build.yml
.github/workflows/dotnet-private-packages-release-build.yml

Updates our JFrog integration for NuGet (.NET) packages.

Update JFrog integration (drop 'scan', keep 'audit')

---

.github/workflows/dotnet-packages-pr-build-jfrog.yml
.github/workflows/dotnet-private-packages-release-build-jfrog.yml

A meta-workflow that does all the individual steps for building / packing / deploying a .NET NuGet
package file.
Includes support for JFrog Artifactory.

Publish the meta workflow for .NET JFrog builds

---

.github/workflows/dotnet-build-jfrog.yml
.github/workflows/dotnet-frogbot-private-repo-scan.yml
.github/workflows/dotnet-packages-pr-build-jfrog.yml
.github/workflows/dotnet-private-packages-release-build-jfrog.yml
.github/workflows/dotnet-push-jfrog-artifactory.yml
.github/workflows/dotnet-test-jfrog.yml

Upgrade JFrog workflows to v1.14.0

---

.github/workflows/dotnet-build-jfrog.yml
.github/workflows/dotnet-packages-pr-build-jfrog.yml

- 'dotnet_restore_verbosity': Provides more information during the restore step.
- 'jfrog_cli_log_level': Set the JFrog CLI log level

Add ability to set debug level on JF CLI / restore

---

.github/workflows/dotnet-build-jfrog.yml
.github/workflows/dotnet-frogbot-private-repo-scan.yml
.github/workflows/dotnet-packages-pr-build-jfrog.yml
.github/workflows/dotnet-private-packages-release-build-jfrog.yml
.github/workflows/dotnet-push-jfrog-artifactory.yml
.github/workflows/dotnet-test-jfrog.yml

Upgrade JFrog workflows to v1.14.1

---

.github/workflows/dotnet-pack-jfrog.yml

Also pass down the JF CLI debug setting from parent.

bug: Add "jf dotnet-config" step before packing

---

forks/github-app-token/action.yml
forks/github-app-token/build.sh
forks/github-app-token/package-lock.json
forks/github-app-token/package.json

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Upgrade github-app-token to Node v20

---

.github/workflows/dotnet-npm-astro-build-test-publish.yml

See: 439d599d3c1841934fdd1c6a77c5b6a45af37dc7
Follow-up for #155

Update dotnet-npm-astro build to create version.json

---

.github/workflows/npm-packages-pr-build.yml
.github/workflows/npm-packages-pr-create-tag.yml
.github/workflows/npm-packages-release-on-tag.yml

This will help reduce the Node16 deprecation warnings.

Upgrade the NPM workflows to use v1.15.5

---

actions/calculate-version-from-txt-using-github-run-id/action.yml

Output the UTC build date and timestamp.

Add build date/timestamp to calculate action

---

.github/workflows/build-dotnet-framework-jfrog.yml

- Builds .NET Framework applications
- Assumes that .NET Framework SDK is installed
- Uses JFrog Artifactory for NuGet package resolution
- Creates a version.json file containing build info
- Publishes an IIS Web Deploy zip file

Add .NET Framework IIS build w/ JFrog + version.json

---

.github/workflows/dotnet-npm-build-jfrog.yml
.github/workflows/dotnet-npm-publish-jfrog.yml
.github/workflows/dotnet-npm-test-jfrog.yml

These are used for .NET builds which also make use of NPM for package resolution.

Create combined .NET / NPM / JFrog workflows
